### ISSUE TITLE
spec_helper.rb not load to global path

### ISSUE THREAD

**Issue by KrDenis** [jbbarth/redmine_base_rspec#2]
My simple spec in a plugin:

```
require "spec_helper"

Rspec.describe CyRecurringInvoicem type: :model do
  it { should have_one(:project) }
end
```

I am  have some changes in your spec_helper.rb:

```
ENV['RAILS_ENV'] ||= 'test'

#load simplecov
if ENV['COVERAGE']
  require 'simplecov'
  SimpleCov.start 'rails' do
    coverage_dir 'tmp/coverage'
###    require "pry"
###    binding.pry
    #exclude core dirs coverage
    add_filter do |file|
      file.filename.include?('/lib/plugins/') || 
        !file.filename.include?('/plugins/')
    end
  end
end

#load rails/redmine
require File.expand_path('../../../../config/environment', __FILE__)

#test gems
require 'rspec/rails'
# require 'rspec/autorun'
require 'rspec/mocks'
require 'rspec/mocks/standalone'

module AssertSelectRoot
  def document_root_element
    html_document.root
  end
end

#rspec base config
RSpec.configure do |config|
  config.mock_with :rspec
  config.filter_run :focus => true
  config.run_all_when_everything_filtered = true
  config.infer_spec_type_from_file_location!
  config.include AssertSelectRoot, :type => :request

  config.include FactoryGirl::Syntax::Methods
  config.use_transactional_fixtures = false
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!

  config.before(:suite) do
    Rails.cache.clear
  end
end
```

Trace error:

```
/usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require': cannot load such file -- spec_helper (LoadError)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/rspec:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/rspec:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by jferreira93** [comment]
I change require 'spec_helper' for require './redmine_base_rspec/spec/spec_helper' and it works fine.
